_wandb:
    value:
        cli_version: 0.18.3
        m:
            - "1": dt
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradient norm
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": CUDA memory
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": CPU memory
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": tokens per second
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
                - 106
            "2":
                - 1
                - 11
                - 49
                - 55
                - 106
            "3":
                - 7
                - 23
                - 55
                - 60
                - 66
            "4": 3.12.5
            "5": 0.18.3
            "6": 4.45.0
            "8":
                - 5
            "9":
                "2": lightning_fabric_logger
            "12": 0.18.3
            "13": linux-x86_64
