_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
                - 106
            "3":
                - 23
                - 55
            "4": 3.12.5
            "5": 0.18.3
            "6": 4.45.0
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
